name: base
channels:
  - fastchan
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - nvidia::cudatoolkit=11.1
  - nvidia::cudnn
  - pytorch>=1.7
  - pytorch-lightning
  - torchmetrics
  - hydra-core
  - einops
  - fastcore>=1.3.8
  - joblib
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - nodejs
  - notebook
  - numpy
  - numpy-base
  - pandas
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - sip
  - six
  - wheel
  - smart_open
  - pytz
  - loguru
  - pydantic
  - rich
  - pip:
      - pyaudio
      - python_speech_features
      - pyautogui
      - audiomentations
      - jupyterlab-code-formatter
      - matplotlib
      - torchtyping
      - torchviz
      - mypy
      - mypy-extensions
      - pyflakes
      - python-telegram-bot
      - pyyaml
      - tabulate
      - tqdm
      - typer
      - wandb
      - natsort
      - toolz
      - cytoolz
      - ujson
      - hydra-colorlog
      - hydra-optuna-sweeper
      - pyrootutils
